# Cloudflare Pages Configuration
name = "jasilmeledath-portfolio"
compatibility_date = "2024-01-01"

[build]
command = "cd client && npm run build"
cwd = "."
watch_dir = "client/src"

[build.environment_variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"

[[redirects]]
from = "/api/v1/*"
to = "https://api.jasilmeledath.dev/api/v1/:path*"
status = 200

[env.production]
NEXT_PUBLIC_API_URL = "https://api.jasilmeledath.dev"
NEXT_PUBLIC_SITE_URL = "https://jasilmeledath.dev"